'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

interface Medicine {
  name: string; dosage: string; duration: string; instructions: string;
}

interface Prescription {
  _id:        string;
  patient:    { name: string; bloodGroup: string; dateOfBirth?: string };
  diagnosis:  string;
  medicines:  Medicine[];
  notes:      string;
  aiGenerated: boolean;
  createdAt:  string;
}

export default function DoctorPrescriptions() {
  const [prescriptions, setPrescriptions] = useState<Prescription[]>([]);
  const [loading, setLoading]             = useState(true);
  const [selected, setSelected]           = useState<Prescription | null>(null);
  const [search, setSearch]               = useState('');

  useEffect(() => {
    fetch('/api/prescriptions')
      .then(r => r.json())
      .then(d => { setPrescriptions(d.prescriptions || []); setLoading(false); });
  }, []);

  const filtered = prescriptions.filter(rx =>
    rx.patient?.name?.toLowerCase().includes(search.toLowerCase()) ||
    rx.diagnosis.toLowerCase().includes(search.toLowerCase())
  );

  // PDF Download
  const downloadPDF = (rx: Prescription) => {
    const doc = new jsPDF();

    doc.setFillColor(79, 70, 229);
    doc.rect(0, 0, 220, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('MediCare Pro', 14, 15);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Doctor Prescription Copy', 14, 23);
    doc.text(`Date: ${new Date(rx.createdAt).toLocaleDateString()}`, 140, 23);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Patient: ${rx.patient?.name}`, 14, 45);
    if (rx.patient?.bloodGroup) doc.text(`Blood Group: ${rx.patient.bloodGroup}`, 14, 52);
    doc.text(`Diagnosis: ${rx.diagnosis}`, 14, 59);
    if (rx.aiGenerated) {
      doc.setFillColor(139, 92, 246);
      doc.rect(14, 63, 35, 6, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text('AI Generated', 16, 67.5);
      doc.setTextColor(0, 0, 0);
    }

    autoTable(doc, {
      startY: 75,
      head: [['Medicine', 'Dosage', 'Duration', 'Instructions']],
      body: rx.medicines.map(m => [m.name, m.dosage, m.duration, m.instructions || 'As directed']),
      headStyles:  { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 247, 255] },
      styles: { fontSize: 9, cellPadding: 4 },
    });

    const finalY = (doc as any).lastAutoTable.finalY + 10;

    if (rx.notes) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text("Doctor's Notes:", 14, finalY);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      const lines = doc.splitTextToSize(rx.notes, 180);
      doc.text(lines, 14, finalY + 7);
    }

    // Signature area
    doc.setDrawColor(200, 200, 200);
    doc.line(130, 270, 195, 270);
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("Doctor's Signature", 140, 276);

    doc.setFillColor(245, 247, 255);
    doc.rect(0, 280, 220, 20, 'F');
    doc.setFontSize(8);
    doc.text('MediCare Pro — Generated by Doctor Portal', 14, 290);

    doc.save(`prescription-${rx.patient?.name}-${rx._id.slice(-6)}.pdf`);
  };

  // Excel Download — ALL prescriptions
  const downloadAllExcel = () => {
    const data = prescriptions.map(rx => ({
      'Patient Name':  rx.patient?.name || '',
      'Blood Group':   rx.patient?.bloodGroup || '',
      'Diagnosis':     rx.diagnosis,
      'Medicines':     rx.medicines.map(m => m.name).join(', '),
      'Total Medicines': rx.medicines.length,
      'AI Generated':  rx.aiGenerated ? 'Yes' : 'No',
      'Notes':         rx.notes || '',
      'Date':          new Date(rx.createdAt).toLocaleDateString(),
    }));

    const ws = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();

    // Column widths
    ws['!cols'] = [
      { wch: 20 }, { wch: 12 }, { wch: 25 },
      { wch: 40 }, { wch: 16 }, { wch: 14 }, { wch: 30 }, { wch: 15 },
    ];

    XLSX.utils.book_append_sheet(wb, ws, 'Prescriptions');
    XLSX.writeFile(wb, `prescriptions-${new Date().toLocaleDateString().replace(/\//g,'-')}.xlsx`);
  };

  // Excel — Single Prescription
  const downloadSingleExcel = (rx: Prescription) => {
    const data = rx.medicines.map(m => ({
      'Medicine Name': m.name,
      'Dosage':        m.dosage,
      'Duration':      m.duration,
      'Instructions':  m.instructions || 'As directed',
    }));

    // Summary sheet
    const summary = [
      { Field: 'Patient',    Value: rx.patient?.name    || '' },
      { Field: 'Blood Group',Value: rx.patient?.bloodGroup || '' },
      { Field: 'Diagnosis',  Value: rx.diagnosis               },
      { Field: 'Date',       Value: new Date(rx.createdAt).toLocaleDateString() },
      { Field: 'AI Generated', Value: rx.aiGenerated ? 'Yes' : 'No' },
      { Field: 'Notes',      Value: rx.notes || ''              },
    ];

    const wb = XLSX.utils.book_new();
    const ws1 = XLSX.utils.json_to_sheet(summary);
    const ws2 = XLSX.utils.json_to_sheet(data);

    ws1['!cols'] = [{ wch: 15 }, { wch: 30 }];
    ws2['!cols'] = [{ wch: 25 }, { wch: 15 }, { wch: 15 }, { wch: 30 }];

    XLSX.utils.book_append_sheet(wb, ws1, 'Summary');
    XLSX.utils.book_append_sheet(wb, ws2, 'Medicines');
    XLSX.writeFile(wb, `rx-${rx.patient?.name}-${rx._id.slice(-6)}.xlsx`);
  };

  return (
    <div className="p-4 md:p-8 max-w-5xl mx-auto">

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-6 md:mb-8">
        <div>
          <h1 className="text-xl md:text-2xl font-bold text-gray-900">Prescriptions</h1>
          <p className="text-gray-500 mt-1 text-sm">{prescriptions.length} prescriptions written</p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <button onClick={downloadAllExcel}
            className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white text-sm font-semibold rounded-xl transition-colors flex items-center gap-2">
            📊 Export All Excel
          </button>
          <Link href="/doctor/prescriptions/new"
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold rounded-xl transition-colors flex items-center gap-2">
            + New Prescription
          </Link>
        </div>
      </div>

      {/* Search */}
      <div className="mb-5">
        <input value={search} onChange={e => setSearch(e.target.value)}
          placeholder="Search by patient name or diagnosis..."
          className="w-full px-4 py-3 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      {loading ? (
        <div className="flex justify-center py-20">
          <div className="animate-spin w-8 h-8 border-4 border-blue-600 border-t-transparent rounded-full" />
        </div>
      ) : (
        <>
          {/* Mobile View */}
          <div className="block lg:hidden space-y-3">
            {filtered.map(rx => (
              <div key={rx._id}
                onClick={() => setSelected(selected?._id === rx._id ? null : rx)}
                className={`bg-white rounded-2xl border-2 p-4 cursor-pointer transition-all ${
                  selected?._id === rx._id ? 'border-blue-500' : 'border-gray-100'
                }`}>
                <div className="flex items-center gap-3 mb-2">
                  <div className="w-10 h-10 bg-purple-100 rounded-xl flex items-center justify-center text-purple-600 font-bold text-lg flex-shrink-0">
                    {rx.patient?.name?.charAt(0)}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-semibold text-sm text-gray-900">{rx.patient?.name}</p>
                    <p className="text-xs text-purple-600 font-medium">{rx.diagnosis}</p>
                  </div>
                  {rx.aiGenerated && (
                    <span className="text-xs bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full flex-shrink-0">🤖</span>
                  )}
                </div>
                <div className="flex justify-between text-xs text-gray-400">
                  <span>{rx.medicines?.length} medicines</span>
                  <span>{new Date(rx.createdAt).toLocaleDateString()}</span>
                </div>

                {/* Expanded on mobile */}
                {selected?._id === rx._id && (
                  <div className="mt-3 pt-3 border-t border-gray-100">
                    <div className="space-y-2 mb-4">
                      {rx.medicines.map((med, i) => (
                        <div key={i} className="bg-gray-50 rounded-xl p-2.5">
                          <p className="font-semibold text-sm text-gray-900">{med.name}</p>
                          <p className="text-xs text-gray-500">{med.dosage} · {med.duration}</p>
                        </div>
                      ))}
                    </div>
                    {rx.notes && (
                      <div className="bg-yellow-50 rounded-xl p-3 mb-3">
                        <p className="text-xs font-semibold text-yellow-700 mb-1">Notes</p>
                        <p className="text-xs text-gray-600">{rx.notes}</p>
                      </div>
                    )}
                    <div className="grid grid-cols-2 gap-2">
                      <button onClick={e => { e.stopPropagation(); downloadPDF(rx); }}
                        className="py-2.5 bg-blue-600 text-white text-xs font-semibold rounded-xl flex items-center justify-center gap-1">
                        📄 PDF
                      </button>
                      <button onClick={e => { e.stopPropagation(); downloadSingleExcel(rx); }}
                        className="py-2.5 bg-green-600 text-white text-xs font-semibold rounded-xl flex items-center justify-center gap-1">
                        📊 Excel
                      </button>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Desktop View */}
          <div className="hidden lg:grid grid-cols-2 gap-5">
            {/* List */}
            <div className="space-y-3">
              {filtered.map(rx => (
                <div key={rx._id} onClick={() => setSelected(rx)}
                  className={`bg-white rounded-2xl border-2 p-4 cursor-pointer hover:shadow-md transition-all ${
                    selected?._id === rx._id ? 'border-blue-500 shadow-md' : 'border-gray-100'
                  }`}>
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-3">
                      <div className="w-11 h-11 bg-purple-100 rounded-xl flex items-center justify-center text-purple-600 font-bold text-lg">
                        {rx.patient?.name?.charAt(0)}
                      </div>
                      <div>
                        <p className="font-semibold text-gray-900 text-sm">{rx.patient?.name}</p>
                        <p className="text-sm text-purple-600 font-medium">{rx.diagnosis}</p>
                      </div>
                    </div>
                    {rx.aiGenerated && (
                      <span className="bg-purple-100 text-purple-700 text-xs font-semibold px-2.5 py-1 rounded-full flex-shrink-0">
                        🤖 AI
                      </span>
                    )}
                  </div>

                  <div className="bg-gray-50 rounded-xl p-3">
                    <p className="text-xs font-semibold text-gray-400 mb-2">
                      MEDICINES ({rx.medicines?.length})
                    </p>
                    <div className="flex flex-wrap gap-1.5">
                      {rx.medicines?.slice(0, 3).map((med, i) => (
                        <span key={i} className="text-xs bg-white border border-gray-200 px-2 py-1 rounded-lg text-gray-700">
                          {med.name}
                        </span>
                      ))}
                      {rx.medicines?.length > 3 && (
                        <span className="text-xs text-gray-400">+{rx.medicines.length - 3} more</span>
                      )}
                    </div>
                  </div>

                  <div className="flex justify-between items-center mt-3">
                    <span className="text-xs text-gray-400">
                      {new Date(rx.createdAt).toLocaleDateString()}
                    </span>
                    <span className="text-xs text-blue-600 font-medium">
                      Click to view →
                    </span>
                  </div>
                </div>
              ))}

              {filtered.length === 0 && (
                <div className="text-center py-16 text-gray-400">
                  <p className="text-4xl mb-2">💊</p>
                  <p>No prescriptions found</p>
                </div>
              )}
            </div>

            {/* Detail Panel */}
            {selected ? (
              <div className="bg-white rounded-2xl border border-gray-100 p-5 h-fit sticky top-6">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="font-bold text-gray-900 text-base">Prescription Detail</h3>
                  {selected.aiGenerated && (
                    <span className="bg-purple-100 text-purple-700 text-xs font-semibold px-2.5 py-1 rounded-full">
                      🤖 AI Generated
                    </span>
                  )}
                </div>

                {/* Patient Info */}
                <div className="bg-blue-50 rounded-xl p-3 mb-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-blue-200 rounded-xl flex items-center justify-center text-blue-700 font-bold">
                      {selected.patient?.name?.charAt(0)}
                    </div>
                    <div>
                      <p className="font-semibold text-gray-900 text-sm">{selected.patient?.name}</p>
                      <div className="flex items-center gap-2 mt-0.5">
                        {selected.patient?.bloodGroup && (
                          <span className="text-xs bg-red-100 text-red-600 px-2 py-0.5 rounded-full font-semibold">
                            {selected.patient.bloodGroup}
                          </span>
                        )}
                        <span className="text-xs text-blue-600 font-medium">{selected.diagnosis}</span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Medicines */}
                <div className="mb-4">
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">
                    Medicines ({selected.medicines?.length})
                  </p>
                  <div className="space-y-2 max-h-48 overflow-y-auto">
                    {selected.medicines?.map((med, i) => (
                      <div key={i} className="bg-gray-50 rounded-xl p-3">
                        <p className="font-semibold text-gray-900 text-sm">{med.name}</p>
                        <div className="flex gap-3 mt-1 text-xs text-gray-500">
                          <span>💊 {med.dosage}</span>
                          <span>⏱ {med.duration}</span>
                          {med.instructions && <span>📝 {med.instructions}</span>}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {selected.notes && (
                  <div className="bg-yellow-50 rounded-xl p-3 mb-4">
                    <p className="text-xs font-semibold text-yellow-700 mb-1">📝 Notes</p>
                    <p className="text-sm text-gray-700">{selected.notes}</p>
                  </div>
                )}

                {/* Download Buttons */}
                <div className="space-y-2">
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">
                    Download Options
                  </p>
                  <div className="grid grid-cols-2 gap-2">
                    <button onClick={() => downloadPDF(selected)}
                      className="py-3 bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold rounded-xl transition-colors flex items-center justify-center gap-2">
                      📄 PDF
                    </button>
                    <button onClick={() => downloadSingleExcel(selected)}
                      className="py-3 bg-green-600 hover:bg-green-700 text-white text-sm font-semibold rounded-xl transition-colors flex items-center justify-center gap-2">
                      📊 Excel
                    </button>
                  </div>

                  <p className="text-xs text-gray-400 text-center mt-2">
                    Prescribed on {new Date(selected.createdAt).toLocaleDateString('en-PK', {
                      day: 'numeric', month: 'long', year: 'numeric'
                    })}
                  </p>
                </div>
              </div>
            ) : (
              <div className="bg-white rounded-2xl border border-gray-100 p-8 text-center text-gray-400 h-fit">
                <p className="text-3xl mb-2">👆</p>
                <p className="text-sm">Select a prescription to view & download</p>
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
}